name: Testing

on:
  push:
    branches:
      - main
    paths: 
      - 'configurations/**'
jobs:
  checks:
    name: Select Environment
    runs-on: ubuntu-latest
    outputs:
      context: ${{ steps.context.outputs.context }}
    steps:
      - name: Select env
        id: context
        run: |
          echo  ${{ github.event.path }}
          if [[ ${{ contains(github.event.path, 'production') }} ]]; then
            echo "::set-output name=context::production"
          else
            echo "::set-output name=context::staging"
          fi
  install:
    runs-on: ubuntu-latest
    needs: [checks]
    defaults:
      run:
        working-directory: configuration/${{ needs.checks.outputs.context }}
    steps:
      - uses: actions/checkout@v3.0.0
      - run: cat test.yml
