name: Testing

on:
  push:
    branches:
      - main
    paths: 
      - 'configurations/**'
jobs:
  checks:
    name: Select Environment
    runs-on: ubuntu-latest
    outputs:
      prod: ${{ steps.changes.outputs.src }}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'configurations/production/**'
  running:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - run: echo "${{ needs.checks.outputs.prod }}"
