name: Testing

on:
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    services:
      minio:
        image: atlastechnologiesteam/minio:latest
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: password
        ports:
          - 9000:9000
    steps:
      - run: |
          curl https://dl.min.io/client/mc/release/linux-amd64/mc \
            --create-dirs \
            -o ./mc \
          &&  chmod +x ./mc
          ./mc alias set storage http://localhost:9000 minio password
