name: Testing

on:
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '8.0' ]
    container: php:${{ matrix.version }}
    steps:
      - run: php --version
