name: Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  checks:
    name: Select Environment
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor }}
      
