name: Testing

on:
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    services:
      minio:
        image: atlastechnologiesteam/minio:latest
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: password
        ports:
          - 9000:9000
    steps:
      - name: Create Minio bucket to tests
        uses: docker://minio/mc:edge
        with:
          entrypoint: ''
          args: |
            mc alias set storage http://minio:9000 minio password
            mc mb storage/files
            mc policy set download storage/files
